trigger:
  - main
  - develop
  - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration)'
      publishWebProjects: true
    displayName: 'dotnet build $(buildConfiguration)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'aks'
      appType: 'webAppLinux'
      WebAppName: 'snehith'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      RuntimeStack: 'DOTNETCORE|6.0'
